<!-- /**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsRma
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */ -->
<?php 
 $_request = $this->getRmaCollection(); ?>
 <?php if($_request->getStatus() != "Completed"){ ?>
<form id="chat_form" method="post" novalidate="novalidate" enctype="multipart/form-data" data-mage-init='{"validation": {}}'>
    <div class="order-history-block">
        <div class="admin__field">
            <label for="message" class="admin__field-label">
              <?php echo __('Message*') ?>
            </label>
            <div>
                <textarea data-validate="{required:true}"
                          name="chat"
                          rows="3"
                          cols="35"
                          id="chat"
                          aria-required="true"
                          class="admin__control-textarea input-text required-entry" style="width: 613px; height: 121px;">
                </textarea>
            </div>
            <div class="admin__field-control">
                <label for="message" class="admin__field-label">
                  <?= __('Attch Your File'); ?>            
                </label>
                <input type="file" name="rma_file" id="rma_file" onchange="validate_fileupload(this);">
                <div style="display: none" class="message error file_error-msg_wrap"><span class="file_error-msg"></span></div>
                <p class="note"><strong><?php echo __("Allowed Types: jpg, jpeg, gif, png, pdf, zip, csv, xlsx");?></strong></p>
            </div>
        </div>
    </div>
    <br>
    <input type="hidden" name="vendor_id" value="<?php echo $_request->getVendorId()?>"></input>
    <button class="button btn btn-success uptransform product-button" title="Save" type="submit" id="save_butn" 
      style="float: none;" onclick="chatForm('<?php echo $this->getUrl('csrma/vrma/chat',array('id'=>$_request->getId()))?>')">
          <span><span><?php echo __('Send Message') ?></span></span>
    </button>
</form>
<?php  } ?>
<br>
<div class="panel panel-default">
      <div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;" >
          <?php echo __('Chat History Information') ?>
      </div>
      <div class="panel-body">
          <?php echo $block->getChildHtml('vendor_rma_history') ?>
      </div>
</div>
<div class="panel panel-default">
      <div class="panel-heading col-md-12" style="text-transform: uppercase;font-weight:bold;padding:4px 15px;">
          <?php echo __('Activity Information') ?>
      </div>
      <div class="panel-body" >
          <?php echo $block->getChildHtml('vendor_rma_notification') ?>
      </div>
</div>
<script>
  require(
    ['jquery'],
    function($) {
        window.chatForm = function (url) {
            $('#chat_form').attr('action',url);
            $('#chat_form').submit();
        };
    });
  var valid = false;
  function validate_fileupload(input_element)
  {require(["jquery"], function ($) {
      var el = document.getElementById("rma_file");
      var fileName = input_element.value;
      var allowed_extensions = new Array("jpg","jpeg","gif","png","pdf","zip","csv","xlsx");
      var file_extension = fileName.split('.').pop(); 
    
      for(var i = 0; i < allowed_extensions.length; i++)
      {
          if(allowed_extensions[i]==file_extension)
          {
              valid = true; // valid file extension
              el.innerHTML = "";
              return;
          }
      }
      el.innerHTML="Invalid file";
      valid = false;
      if(!valid){
      	$('#rma_file').val('');
      	$('.file_error-msg').text("Invalid File Type");
      	$('.file_error-msg_wrap').show();
      }else{
      	 $('.file_error-msg_wrap').hide();
      	 $('.file_error-msg').text("");
          }
  });   
  }
</script>

