<?php 
$request = $this->_objectManager->get('Magento\Framework\App\Request\Http');
$layout = $request->getFullActionName();
if('catalog_product_view' == $layout)
{
	$purchasedPlans = $block->sliderData();
	$url = $this->getBaseUrl().'pub/media/advertisement/';?>
	<?php if(count($purchasedPlans)){?>
		<div class="advertisement_product_info_poistion">
			<div class="advertisement_product_info_slider owl-carousel sidebar-slider">
				<?php foreach ($purchasedPlans as $purchasedPlan): ?>
					<?php if(count($purchasedPlans) > 1){?>
						<div class="item advertisement_product_info_item">
							<a target="_blank"  href="<?php echo $purchasedPlan->getBlockUrl();?>"><img src="<?php echo $url.$purchasedPlan->getBlockImage()?>"></a>
						</div>
					<?php }else{?>
						<div class="item advertisement_product_info_image">
							<a target="_blank" href="<?php echo $purchasedPlan->getBlockUrl();?>"><img src="<?php echo $url.$purchasedPlan->getBlockImage()?>"></a>
						</div>
					<?php }?>
				<?php endforeach ?>	
			</div>		
		</div>
		<script type="text/javascript">
			require([
		        'jquery',
		        'Ced_Advertisement/js/owlcarousel/owl.carousel'
		    ], function ($) {
		    	var isNav = false;
		        var navText = '';
		        var loop = false;
		        var totalItems = $('.advertisement_product_info_item').length;
		        if (totalItems > 6) {
		            isNav = true;
		            navText = ["<i class='fa fa-angle-left' aria-hidden='true'></i>", "<i class='fa fa-angle-right'></i>"];
		            loop = true;
		        }
		    	$('.advertisement_product_info_slider').owlCarousel({
		    		autoplay: true,
		            autoplayTimeout: 5000,
		            autoplayHoverPause: true,
				    loop:loop,
				    navRewind: true,
				    nav:isNav,
				    navText: navText,
				    dots: false,
		            items:1
				});
		    });	
		</script>

		<style type="text/css">
			.advertisement_product_info_slider .item img {
			  max-width: 100%;
			  width: 100%;
			}
		</style>
<?php }}?>