<?php $data = $block->getBlocksData();
$url = $this->getBaseUrl().'pub/media/advertisement/';?>
<div>
	<div class="col-md-12">
		<div>
			<div class="panel-heading col-md-12 uptransform">

                <?php echo $block->getBlockId() ? __('Edit Advertisement Blocks') : __('New Advertisement Blocks');?>
                <button type="submit" title="Edit" onclick="blockEdit();" class="button btn btn-primary uptransform">
                    <span>
                        <span><?php echo __('Save');?></span>
                    </span>
                </button>
                <?php if($data && $data->getId()){?>
                <button type="button" title="Edit" onclick="blockDelete();" class="button btn btn-primary uptransform">
                    <span>
                        <span><?php echo __('Delete');?></span>
                    </span>
                </button>
                <?php }?>
            </div>
		</div>
		<div>
			<ul class="form-list">
				<form enctype="multipart/form-data" method="post" action="<?php echo $this->getUrl('advertisement/blocks/save');?>" id="block_edit_form" novalidate="novalidate">
					<li class="wide">
						<label for="title" class="label admin__field-label">
							<span>* <?php echo __('Title');?></span>
						</label>
						<div class="input-box">
							<input type="hidden" class="required-entry" value="<?php if($data && $data->getId()){echo $data->getId();}?>" name="id" id="id">
							<input type="text" class="required-entry" value="<?php if($data && $data->getTitle()){echo $data->getTitle();}?>" name="title" id="title">
						</div>
					</li>
					<li class="wide">
						<label for="url" class="label admin__field-label">
							<span>* <?php echo __('Url');?></span>
						</label>
						<div class="input-box">
							<input type="text" class="required-entry" value="<?php if($data && $data->getUrl()){echo $data->getUrl();}?>" name="url" id="url">
						</div>
					</li>
					<li class="wide">
						<label for="image" class="label admin__field-label">
							<span>* <?php echo __('Image');?></span>
						</label>
						<div class="input-box">
							<input type='file' value="<?php if($data && $data->getImage()){ echo $url.$data->getImage();}?>" class="required-entry" onchange="readURL(this);" name="image" id="image" />
							<img id="block_image_preview" src="<?php if($data && $data->getImage()){ echo $url.$data->getImage();}?>" alt="" />

						</div>
					</li>
				</form>
			</ul>
		</div>
	</div>
</div>
<script type="text/javascript">
	function blockEdit(){
		require(['jquery'], function($){
			var ret = $('#block_edit_form').valid();    
            if(ret==true){
				$('#block_edit_form').submit();
			}
		});
	}

	function readURL(input) {
		require(['jquery'], function($){
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#block_image_preview')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        });
    }

    function blockDelete(){
    	window.location.href = "<?php echo $this->getUrl('advertisement/blocks/delete',['id' => $data['id']])?>";
    }

    require(["jquery","mage/mage"],function($){ 
        $('#block_edit_form').mage('validation', {
            
        });
     });
</script>
