<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Rewardsystem
 * @author   	 CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php $Param = $this->getRequest()->getParams();$referCode ='';
if(isset($Param['refer_code']))
{
	$referCode = $Param['refer_code'];
}
?>

    
    <div class="field regulation">
       
        <div class="control">
            <input style="display: none" type="text" name="refer_code" id="refer_code"  class="input-text" value="<?php echo $referCode ?>" data-validate="{required:false}">
        </div>
     
    </div>
