<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_RequestToQuote
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/**
 * Quote cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */
if ($block->getItemsCount() > 0) {
    echo $block->getChildHtml('quote-items');
} else { ?>
    <div class="cart-empty">
	    <p><?php /* @escapeNotVerified */ echo __('You have no items in your requested quotations.') ?></p>
	    <p><?php /* @escapeNotVerified */ echo __('Click <a href="%1">here</a> to continue shopping.',
	            $this->getBaseUrl()) ?></p>
	</div>
<?php } ?>
